name: core
description: core
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  designsystem:
    path: ../designsystem

  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
