name: designsystem
description: designsystem
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  go_router: ^15.1.2
  flutter_svg: ^2.1.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
