// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQo9SKgDH6QV5Zly-Qce1cw-VwAcJ_VmA',
    appId: '1:751054819007:android:05d9aa4b530a77f880800a',
    messagingSenderId: '751054819007',
    projectId: 'lottoz-467408',
    storageBucket: 'lottoz-467408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KtIeT9sAW4hX0_h5HpCMszU_OjcEtFs',
    appId: '1:751054819007:ios:9e04e6639aed292880800a',
    messagingSenderId: '751054819007',
    projectId: 'lottoz-467408',
    storageBucket: 'lottoz-467408.firebasestorage.app',
    androidClientId: '751054819007-2f1vfrpicbtthuop8pcndij2enp1phsd.apps.googleusercontent.com',
    iosClientId: '751054819007-kmhkuav3thn3hluem2u64t70222uc87u.apps.googleusercontent.com',
    iosBundleId: 'info.devalor.lottoz',
  );
}
